version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn run start-watch
    environment:
      API_BASE_URL: '${API_BASE_URL-http://nearby-services-api:3001}'
      DISABLE_GOOGLE_SEARCH: ${DISABLE_GOOGLE_SEARCH}
      DATE: ${DATE}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_LOG_LEVEL: ${NEW_RELIC_LOG_LEVEL}
  frontend:
    extends:
      service: base-app
    links:
      - nearby-services-api:nearby-services-api
    ports:
      - 3000:3000
    volumes:
      - c2s-node_modules:/code/node_modules
      - .:/code

  nearby-services-api:
    image: "nhsuk/nearby-services-api:${NEARBY_SERVICES_API_DOCKER_IMAGE_TAG-0.14.1}"
    links:
      - pharmacy-db-elastic:es

  pharmacy-db-elastic:
    image: "nhsuk/elasticsearch-updater-snapshot:20170921"

volumes:
  c2s-node_modules:
