version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn start-watch
    environment:
      BUSINESS_HOURS_END_HOUR: ${BUSINESS_HOURS_END_HOUR}
      BUSINESS_HOURS_END_MINUTE: ${BUSINESS_HOURS_END_MINUTE}
      BUSINESS_HOURS_START_HOUR: ${BUSINESS_HOURS_START_HOUR}
      BUSINESS_HOURS_START_MINUTE: ${BUSINESS_HOURS_START_MINUTE}
      DATETIME: ${DATETIME}
      SEARCH_API_KEY: ${SEARCH_API_KEY}
      SEARCH_API_HOST: ${SEARCH_API_HOST}
      SEARCH_MAX_RESULTS: ${SEARCH_MAX_RESULTS}
      SEARCH_API_VERSION: ${SEARCH_API_VERSION}
  frontend:
    extends:
      service: base-app
    ports:
      - 3000:3000
    volumes:
      - c2s-node_modules:/code/node_modules
      - .:/code

volumes:
  c2s-node_modules:
