version: '2.1'

services:

  tests:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run git-hook
    volumes:
      - c2s-tests-node_modules:/code/node_modules
    environment:
      NODE_ENV: test
    links:
      - nearby-services-api:nearby-services-api

  travis-tests:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run travis
    user: root
    volumes:
      - .:/code
      - c2s-travis-tests-node_modules:/code/node_modules
    environment:
      API_BASE_URL: 'http://nearby-services-api:3001'
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
      - nearby-services-api:nearby-services-api

  nearby-services-api:
    image: "nhsuk/nearby-services-api:${NEARBY_SERVICES_API_DOCKER_IMAGE_TAG-0.5.2}"
    links:
      - pharmacy-db:mongo

  pharmacy-db:
    image: "nhsuk/pharmacy-db:${PHARMACY_DB_DOCKER_IMAGE_TAG-0.1.0}"

volumes:
  c2s-tests-node_modules:
  c2s-travis-tests-node_modules:
